### ISSUE TITLE
大量的 warning C4804: “<”: 在操作中使用类型“bool”不安全

### ISSUE THREAD

**Issue by microIBM** [yigao/NFShmXFrame#2]
E:\GitHub\NFShmServer\game\MMO\NFLogicComm\DescStore\MonsterCollectDesc.cpp(67,21): warning C4804: “<”: 在操作中使用类型“bool”不安全

应该把has_m_id()改成m_id()函数
if (m_minId == INVALID_ID)
{
	m_minId = desc.m_id();
}
else
{
	if (desc.m_id() < m_minId)
	{
		m_minId = desc.m_id();
	}
}

**Comment by yigao** [comment]
ok! thank you!
